feat: working multigpu

diff --git a/mkosi.extra/usr/local/bin/tinfoil-boot b/mkosi.extra/usr/local/bin/tinfoil-boot
--- a/mkosi.extra/usr/local/bin/tinfoil-boot
+++ b/mkosi.extra/usr/local/bin/tinfoil-boot
@@ -55,6 +55,61 @@ mount -t tmpfs -o size=512M tmpfs /tmp
 
 mkdir -p /mnt/ramdisk/vllm/run
 
+source /opt/venv/bin/activate
+
+# Check for GPUs
+if lspci | grep -i nvidia > /dev/null; then
+    # Check if at least 12 nvidia devices are present (8 GPUs + 4 NVSwitches)
+    if [ $(lspci | grep -i nvidia | wc -l) -ge 12 ]; then
+        echo "Multi-GPU detected, enabling PPCIe"
+        # HACK: This is horrible, need to fix
+        systemctl stop nvidia-fabricmanager
+        systemctl stop nvidia-persistenced
+        for mod in nvidia_drm nvidia_modeset nvidia_uvm ecdsa_generic; do
+            rmmod $mod || true
+        done
+
+        max_attempts=10
+        attempt=1
+        while [ $attempt -le $max_attempts ]; do
+            if rmmod nvidia; then
+                break
+            else
+                echo "Failed to remove nvidia module (attempt $attempt of $max_attempts)"
+                if [ $attempt -lt $max_attempts ]; then
+                    echo "Waiting 5 seconds before retry..."
+                    sleep 5
+                else
+                    echo "Failed to remove nvidia module after $max_attempts attempts"
+                    exit 1
+                fi
+            fi
+            attempt=$((attempt + 1))
+        done
+
+        sleep 5
+        modprobe ecdsa_generic ecdh
+        modprobe --ignore-install nvidia NVreg_RegistryDwords="RmEnableProtectedPcie=0x1"
+        sleep 5
+        systemctl start nvidia-fabricmanager
+        systemctl start nvidia-persistenced || true  # NATE: This isn't working right and might be causing perf issue
+    else
+        echo "Less than 12 NVIDIA devices detected, not enabling PPCIe"
+        echo "Loading nvidia driver..."
+        modprobe ecdsa_generic ecdh
+        modprobe --ignore-install nvidia
+    fi
+
+    # Verify GPU attestation
+    echo "Verifying GPU attestation..."
+    python3 -m verifier.cc_admin
+
+    # Manual override
+    # nvidia-smi conf-compute -srs 1
+else
+    echo "No GPU(s) detected"
+fi
+
 if [ ! -e /dev/sdb ]; then
     echo "No config disk found"
     exit 1
@@ -74,24 +129,6 @@ else
 fi
 
 dd if=/dev/sdc bs=1 status=none | tr -d '\0' > /mnt/ramdisk/external-config.yml
-
-source /opt/venv/bin/activate
-
-# Check for GPUs
-if lspci | grep -i nvidia > /dev/null; then
-    echo "Loading nvidia driver..."
-    /sbin/modprobe ecdsa_generic ecdh
-    /sbin/modprobe --ignore-install nvidia
-
-    # Verify GPU attestation
-    echo "Verifying GPU attestation..."
-    python3 -m verifier.cc_admin
-
-    # Manual override
-    # nvidia-smi conf-compute -srs 1
-else
-    echo "No GPU(s) detected"
-fi
 
 # Mount MPK and set up containers
 tinfoil-setup
